---
title: Data
description: We describe the sources of our data and the cleaning process.
toc: true
draft: false
---

<span style="font-size: 24px;">**Fatal Police Shootings Data**</span>

Our first data set contains information on every fatal shooting made by a police officer in the US. This data was initially collected since the FBI and the Centers for Disease Control and Prevention log fatal shootings by police, but officials acknowledge that their data is incomplete. To combat this, our dataset aims to create a more comprehensive picture of police shootings, in what cases they come about, and which demographic groups these shootings tend to involve.

We are using data from `fatal-police-shootings-data.csv` with 14 variables:

* **Id**: Presumably their criminal ID number. It is not specific to the order of the date of the shooting, so I think it is assigned based on another variable.
* **Name**: The name of the person that got shot.
* **Date**: The day they were shot, from January 2015 - June 2020.
* **Manner_of_death**: How they were killed by the police (shot/shot and tasered).
* **Armed**: Whether they were carrying a “weapon” at the time of arrest and shooting.
* **Age**: Age when shot.
* **Gender**: Indicates whether male or female.
* **Race**: 
    - A = Asian
    - W = White
    - H = Hispanic
    - B = Black
    - N = Native American
    - O = Other
* **City**: Location where they were shot.
* **State**: What state the city is in.
* **Signs_of_mental_illness**: Whether or not the person shot was mentally ill.
* **Threat_level**: Indicates whether the police were in a threatened position (attack or other).
* **Flee**: Method of fleeing if they were, or if they weren’t.
* **Body_camera**: Whether the police were using a body camera during the arrest and shooting.

Our dataset was fairly clean when we found it, making it relatively easy to interpret and work with. However, our “Race” variable is given by letters - A, W, H, B, N, and O - so are making an extra column “Race_Full” that has the full names of these variables such as “Asian” instead of “A” and “Native American” instead of “N”.

The cleaned data could be found here: [Cleaned Dataset 1](load_and_clean_data.R)


----

<span style="font-size: 24px;">**Giffords Law Center's 2022 Scorecard**</span>

Our second dataset, sourced from the Giffords Law Center, provides a comprehensive overview of gun policy strength across US states. This data is meticulously curated to assess the effectiveness of various gun laws and identify areas for potential reform. By analyzing this dataset, we aim to uncover correlations between gun policy strength and gun violence rates.

We are using data from `US_Gun_Statistics_Full_Data.csv` with 7 variables:

* **state**: The name of the US state.
* **raw_score**: The raw score assigned to the state based on its gun policy strength.
* **murders**: The total number of murders in the state.
murders_with_firearms: The number of murders committed with firearms in the state.
* **active_shooter_deaths**: The number of deaths resulting from active shooter incidents in the state.
* **suicides_with_firearms**: The number of suicides committed with firearms in the state.
* **population**: The total population of the state.

The data can be found here [Dataset 2](US_Gun_Statistics_Full_Data.csv)


----

<span style="font-size: 24px;">**Merged Dataset**</span>

To combine our datasets, we first addressed the inconsistency in state names. We created a new column in our original dataset that included both the state abbreviation and the full state name. This allowed us to merge the datasets based on this common column.

Several irrelevant columns were removed during the cleaning process, including 'Flee', 'id', 'body_camera', and 'officer name'. Additionally, we corrected errors in the state data, such as treating "DC" as a separate state and consolidating duplicate entries for Nevada. Finally, we removed any extra or incomplete rows to ensure data accuracy.

The code used for merging and cleaning the datasets can be found here [Merging Datasets Code](merging_dataset.qmd)

The final merged dataset is available here [Final Merged Dataset](merged_dataset.csv)
