---
title: "Blog Post 7"
author: "Team thirteen"
date: "2024-12-04"
date-modified: "2024-12-04"
draft: FALSE
---

**How are we continuing our exploratory data analysis?**
We are deepening our exploratory data analysis by analyzing interaction between race, gender, age, and situational factors like threat level and armed status, adjusted for population proportion. Additionally, we are merging external dataset, such as the Giffords Law Center’s gun law scorecard, to explore the correlation between gun legislation and shooting rates. Visualizations, including an interactive map highlighting state level trends and disparities, are developed to enhance insights.
Based on the EDA we have done so far, we got the most significant insight when comparing police shootings and racial proportions by state. To further delve into this analysis, we plan to make an interactive map using the shiny package. This visual will include two maps of the United States. The first will give insight about the frequency of fatal police shootings by population per state, while the second will have the population proportion of various racial groups where the viewer can choose which race to look into. Having these two maps side-by-side allows the user to see overlaps in how race interacts with shootings in the form of a map. 

**Our Thesis**
Police shootings occur more frequently in states with higher proportions of people of color, specifically Black, Native American, and Hispanic people. 

**How we plan to refine our visualizations and tables?** 
We are adjusting our dataset to include summary statistics of race populations in each state. This will allow for visualizations that are relevant to the frequency of police brutality in relation to race and a broad comparison between states. 
We plan to further polish our existing visuals by adding applicable axis titles, captions for clarity, color codes, and annotations when necessary. All of these changes serve to make our visualizations and tables easier to understand and draw insight from. 
